baseURL = "https://securek8s.dev/"
languageCode = "en-us"
title = "Kubernetes Built-in Controls Workshop"
theme = "ananke"
copyright = "Connor Gilbert and StackRox, Inc."

googleAnalytics = "UA-145376512-4"

menus = ["main"]

Paginate = 15
SectionPagesMenu = ["section"]

[params]
  mainSections = ["post"] # Disable recent-content widget by using a non-existent content type
  recent_posts_number = 0
  custom_css = [
    "assets/css/code-embed.css",
    "assets/css/download-link.css",
  ]

[markup]
  [markup.highlight]
    tabWidth = 2
