apiVersion: v1
kind: Namespace
metadata:
  name: buggy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy
  namespace: buggy
  labels:
    app: buggy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy
  template:
    metadata:
     labels:
       app: buggy
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: connorg/memory-exploder:0.0.0
        name: buggy
---
apiVersion: v1
kind: Service
metadata:
  name: buggy
  namespace: buggy
spec:
  selector:
    app: buggy
  ports:
    - name: https
      protocol: TCP
      nodePort: 31304
      port: 31304
      targetPort: 80
  type: NodePort
