apiVersion: v1
kind: Namespace
metadata:
  name: nonroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: nonroot
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
       app: server
  template:
    metadata:
     labels:
       app: server
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: connorg/simple-server:0.0.1-nonroot
        name: server
        imagePullPolicy: Always
        command: ["/main", "-logPath", "", "-addr", "0.0.0.0:8080"]
        volumeMounts:
          - {name: allofetc, mountPath: /host/etc}
      volumes:
        - {name: allofetc, hostPath: {path: /etc}}
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: nonroot
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      nodePort: 31303
      port: 31303
      targetPort: 8080
  type: NodePort
