apiVersion: v1
kind: Namespace
metadata:
  name: smoke-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: smoke-test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
     labels:
       app: nginx
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: smoke-test
spec:
  selector:
    app: nginx
  ports:
    - name: https
      protocol: TCP
      nodePort: 30000
      port: 30000
      targetPort: 80
  type: NodePort
